version = 0.1

[default.deploy.parameters]
stack_name = "projeto-aws-alunos"
resolve_s3 = true
s3_prefix = "projeto-aws-alunos"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
