name: Deploy Lambda com AWS SAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Build SAM
        run: |
          sam build

      - name: Deploy SAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          sam deploy --no-confirm-changeset --stack-name projeto-aws-alunos --capabilities CAPABILITY_IAM --resolve-s3