name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar SAM CLI
        run: pip install aws-sam-cli

      - name: Build SAM
        run: sam build

      - name: Deploy Dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          sam deploy --stack-name projeto-aws-dev --capabilities CAPABILITY_IAM --resolve-s3 --no-confirm-changeset
